# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: orchestrator.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'orchestrator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12orchestrator.proto\"J\n\x0ePipelineConfig\x12\x11\n\tblueprint\x18\x01 \x01(\t\x12\x12\n\ndockerinfo\x18\x02 \x01(\t\x12\x11\n\tprotoszip\x18\x03 \x01(\x0c\"8\n\x0ePipelineStatus\x12\x12\n\nstatusCode\x18\x01 \x01(\x05\x12\x12\n\nstatusText\x18\x02 \x01(\t2I\n\x12start_orchestrator\x12\x33\n\x0f\x65xecutePipeline\x12\x0f.PipelineConfig\x1a\x0f.PipelineStatusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'orchestrator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PIPELINECONFIG']._serialized_start=22
  _globals['_PIPELINECONFIG']._serialized_end=96
  _globals['_PIPELINESTATUS']._serialized_start=98
  _globals['_PIPELINESTATUS']._serialized_end=154
  _globals['_START_ORCHESTRATOR']._serialized_start=156
  _globals['_START_ORCHESTRATOR']._serialized_end=229
# @@protoc_insertion_point(module_scope)
